### PR TITLE
Added recursive folder totals for html report.

### PR DESCRIPTION
**Pull request by moos**

### CODE REVIEW

**Comment by moos** [comment]
Sample.
screen shot 2016-08-29 at 1 43 28 pm

Depth slider example:
screen shot 2016-08-29 at 2 19 05 pm

These are shown only on root index file.  Tested on IE8+ and latest browsers.

**Comment by tmac4096** [comment]
Great work! Could you please send a PR to merge this back to gotwarlost/istanbul? I think many guys want a recursive folder report view. Thanks!

**Comment by moos** [comment]
@tmac4096 gotwarlost has been dormant for a while.  This feature is available now on npm as [istanbul-moos](https://www.npmjs.com/package/istanbul-moos).

**Comment by moos** [comment]
Merged into master and published as 0.4.5-moos.4

**Pull request closed without merging**
